{{- if .Values.exportarr.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "radarr.chart" . }}
  {{- with .Values.exportarr.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radarr.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: monitoring
    interval: {{ .Values.exportarr.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.exportarr.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.exportarr.serviceMonitor.path }}
{{- end }}
